config/routes.rb
Rails.application.routes.draw do

  root 'public#index'

  get "login" => "accounts#login", as: :login
  get "logout" => "accounts#logout", as: :logout

  post "authenticate" => "accounts#authenticate", as: :authenticate

  get "public/:listing_id/details" => "public#details", as: :details

  resources :users do
    resources :listings do
      resources :features
      resources :pictures
    end
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	validates :title, presence: true
	belongs_to :user
	has_many :features, dependent: :destroy
	has_many :pictures, dependent: :destroy
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  	@listings = @user.listings
  end

  def new
    @user = User.find(params[:user_id])
    @listing = Listing.new
  end

  def create
    @user = User.find(params[:user_id])
    @listing = Listing.new(listing_params)
    @listing.user = @user
    if @listing.save
      redirect_to controller: "listings", action: "index"
    else
      redirect_to controller: "listings", action: "new"
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @listing = Listing.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to controller: "listings", action: "index"
    else
      render "new"
    end
  end

  def show
  end

  def destroy
    @user = User.find(params[:user_id])
    @listing = Listing.find(params[:id])
    if @listing.destroy
      redirect_to controller: "listings", action: "index"
    else
        redirect_to controller: "listings", action: "index"
    end
  end

  private

    def listing_params
      params.require(:listing).permit(:user_id, :title, :description, :price, :id)
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for [@user, @listing], :html => {class: "form-horizontal"} do |f| %>
<% if @listing.errors.any? %>
  <div class="form-group">
  	<div id="error_explanation">
  		<h3>
  			<%= pluralize(@listing.errors.count, "error") %>
  			prohibited this listing from being saved.
  		</h3>
  	</div>
  </div>
<% end %>
<div class="form-group">
	<div class="control-label col-md-2">
		<%= f.label :title %>
	</div>
	<div class="col-md-6">
    <%= f.text_field :title, {:class => "form-control input-md", :maxlength => "140"} %>
	</div>
</div>
<div class="form-group">
	<div class="control-label col-md-2">
		<%= f.label :description %>
	</div>
	<div class="col-md-6">
    <%= f.text_field :description, {:class => "form-control input-md", :maxlength => "255"} %>
	</div>
</div>
<div class="form-group">
	<div class="control-label col-md-2">
		<%= f.label :price %>
	</div>
	<div class="col-md-2">
    <%= f.text_field :price, {:class => "form-control input-md", :maxlength => "16"} %>
	</div>
</div>
<div class="form-group">
	<div class="col-md-12 text-center">
		<%= f.submit "Save", {class: "btn btn-primary btn-md"} %>
	</div>
</div>

<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<%= render "form" %>

app/views/listings/index.html.erb
<h1 class="page-heading">All Listings</h1>

<div class="row">
	<div class="col-md-12">
		<%=link_to 'New', new_user_listing_path(@user), {class: "btn btn-primary btn-md"}%>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<% if @listings.length == 0 %>
		  <p class="lead"> No listings found </p>
		<% else %>

			<table class="table table-bordered table-striped table-responsive">
				<thead>
					<tr>
						<td>Title</td>
						<td>Description</td>
						<td>Price</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</thead>
				<tbody>
		      <% @listings.each do |listing| %>
		      	<tr>
		      		<td><%= listing.title %></td>
		      		<td><%= listing.description %></td>
		      		<td><%= listing.price %></td>
		      		<td><%= link_to "Features", user_listing_features_path(@user, listing) %></td>
		      		<td><%= link_to "Pictures", user_listing_pictures_path(@user, listing) %></td>
							<td><%= link_to "Edit", edit_user_listing_path(@user, listing)%></td>
							<td><%= link_to "Delete", [@user, listing], method: :delete, data: {confirm: "Are you sure?"} %></td>
		      	</tr>
		      <% end %>
	    	</tbody>
			</table>
		<% end %>
  </div>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>
<%= render "form" %>