config/routes.rb
Rails.application.routes.draw do

  root 'public#index'

  get "login" => "accounts#login", as: :login
  get "logout" => "accounts#logout", as: :logout

  post "authenticate" => "accounts#authenticate", as: :authenticate

  get "public/:listing_id/details" => "public#details", as: :details

  resources :users do
    resources :listings do
      resources :features
      resources :pictures
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :listings

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: {minimum: 8}, allow_nil: true
  validates :usertype, presence: true

  def to_s
  	"#{firstname} " + "#{lastname}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in
  before_action :checkAuth

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to controller: "users", action: "index"
    else
      redirect_to controller: "users", action: "index"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
      redirect_to controller: "users", action: "index"
    else
      redirect_to controller: "users", action: "index"
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to controller: "users", action: "index"
    else
      redirect_to controller: "users", action: "index"
    end
  end

  private

    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :usertype)
    end

    def checkAuth
      is_authorized("Admin")
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => {class: "form-horizontal"} do |f| %>
<% if @user.errors.any? %>
  <div class="form-group">
  	<div id="error_explanation">
  		<h3>
  			<%= pluralize(@user.errors.count, "error") %>
  			prohibited this listing from being saved.
  		</h3>
  	</div>
  </div>
<% end %>
<div class="form-group">
	<div class="control-label col-md-2">
		<%= f.label :firstname %>
	</div>
	<div class="col-md-6">
    <%= f.text_field :firstname, {:class => "form-control input-md", :maxlength => "140"} %>
	</div>
</div>
<div class="form-group">
	<div class="control-label col-md-2">
		<%= f.label :lastname %>
	</div>
	<div class="col-md-6">
    <%= f.text_field :lastname, {:class => "form-control input-md", :maxlength => "140"} %>
	</div>
</div>
<div class="form-group">
	<div class="control-label col-md-2">
		<%= f.label :email %>
	</div>
	<div class="col-md-6">
    <%= f.text_field :email, {:class => "form-control input-md", :maxlength => "140"} %>
	</div>
</div>
<div class="form-group">
	<div class="control-label col-md-2">
		<%= f.label :password %>
	</div>
	<div class="col-md-6">
    <%= f.text_field :password, {:class => "form-control input-md", :maxlength => "140"} %>
	</div>
</div>
<div class="form-group">
	<div class="control-label col-md-2">
		<%= f.label :usertype %>
	</div>
	<div class="col-md-6">
    <%= f.text_field :usertype, {:class => "form-control input-md", :maxlength => "255"} %>
	</div>
</div>
<div class="form-group">
	<div class="col-md-12 text-center">
		<%= f.submit "Save", {class: "btn btn-primary btn-md"} %>
	</div>
</div>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>New User</h1>
<%= render "form" %>

app/views/users/index.html.erb
<h1 class="page-heading">All Users</h1>

<div class="row">
	<div class="col-md-12">
		<%=link_to 'New', new_user_path, {class: "btn btn-primary btn-md"}%>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<% if @users.length == 0 %>
		  <p class="lead"> No users found </p>
		<% else %>

			<table class="table table-bordered table-striped table-responsive">
				<thead>
					<tr>
						<td>Email</td>
						<td>Last Name</td>
						<td>User Type</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</thead>
				<tbody>
		      <% @users.each do |user| %>
		      	<tr>
		      		<td><%= user.email %></td>
		      		<td><%= user.lastname %></td>
		      		<td><%= user.usertype %></td>
		      		<td><%= link_to "Listings", user_listings_path(user) %></td>
							<td><%= link_to "Edit", edit_user_path(user)%></td>
							<td><%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure?"} %></td>
		      	</tr>
		      <% end %>
	    	</tbody>
			</table>
		<% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render "form" %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>