config/routes.rb
Rails.application.routes.draw do

  root 'public#index'

  get "login" => "accounts#login", as: :login
  get "logout" => "accounts#logout", as: :logout

  post "authenticate" => "accounts#authenticate", as: :authenticate

  get "public/:listing_id/details" => "public#details", as: :details

  resources :users do
    resources :listings do
      resources :features
      resources :pictures
    end
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	validates :filename, presence: true
	belongs_to :listing
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  	@listing = Listing.find(params[:listing_id])
  	@pictures = @listing.pictures
  end

  def new
    @user = User.find(params[:user_id])
  	@listing = Listing.find(params[:listing_id])
  	@picture = Picture.new
  end

  def create
    listingId = params[:listing_id]
    @listing = Listing.find(listingId)

    @picture = Picture.new(picture_params)

    @picture.listing = @listing

    uploadIO = params[:picture][:image]
    if uploadIO != nil
      t = Time.now
      ext = File.extname(uploadIO.original_filename)
      tmpFilename = "file_#{t.strftime("%Y%m%d%H%M")}" + ext
      @picture.filename = tmpFilename
      filename = Rails.root.join("public", "images", tmpFilename)
      File.open(filename, "wb") do |file|
        file.write(uploadIO.read)
      end
    end

    if @picture.save
      redirect_to controller: "pictures", action: "index"
    else
      render "new"
    end
  end

  def show
    @listing = Listing.find(params[:listing_id])
    @picture = @listing.pictures.find(params[:id])

  end

  def edit
    @user = User.find(params[:user_id])
  	@listing = Listing.find(params[:listing_id])
  	@picture = @listing.pictures.find(params[:id])
  end

  def update
    listingId = params[:listing_id]
    @listing = Listing.find(listingId)

    @picture = @listing.pictures.find(params[:id])
    uploadIO = params[:picture][:image]

    if uploadIO != nil
      if @picture.filename != nil
        filename = Rails.root.join("public", "images", @picture.filename)
        File.delete(filename) if File.exist?(filename)
      end
      t = Time.now
      ext = File.extname(uploadIO.original_filename)

      tmpFilename = "file_#{t.strftime("%Y%m%d%H%M")}" + ext

      @picture.filename = tmpFilename

      filename = Rails.root.join("public", "images", tmpFilename)

      File.open(filename, "wb") do |file|
        file.write(uploadIO.read)
      end

    end

    if @picture.update(picture_params)
      redirect_to controller: "pictures", action: "index"
    else
      render "edit"
    end 
      
  end

  def destroy
    listingId = params[:listing_id]
    listing = Listing.find(listingId)

    picture = listing.pictures.find(params[:id])

    if picture.filename != nil
      filename = Rails.root.join("public", "images", picture.filename)
      File.delete(filename) if File.exist?(filename)
    end

    listing.pictures.destroy(picture)
    redirect_to controller: "pictures", action: "index"
  end

  private

    def picture_params
      params.require(:picture).permit(:listing_id, :title)
    end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for [@user, @listing, @picture], :html => {:multipart => true, :class => "form-horizontal"} do |f| %>
	<% if @picture.errors.any? %>
  <div class="form-group">
  	<div id="error_explanation">
  		<h3>
  			<%= pluralize(@picture.errors.count, "error") %>
  			prohibited this picture from being saved.
  		</h3>
  	</div>
  </div>
	<% end %>

	<div class="form-group">
		<div class="control-label col-md-2">
			<%= f.label :title %>
			</div>
			<div class="col-md-4">
			<%= f.text_field :title, {:class => "form-control input-md", :maxlength => "140"} %>
		</div>
	</div>


	<div class="form-group">
		<div class="control-label col-md-2">
			<label> Select File</label>
			</div>
			<div class="col-md-4">
			<%= f.file_field :image, {:class => "form-control input-md"} %>
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-12 text-center">
		<%= f.submit "Save", {class: "btn btn-primary btn-md"} %>
		</div>
	</div>


<% end %>

app/views/pictures/edit.html.erb
<h1>New Picture</h1>
<%= render "form" %>

app/views/pictures/index.html.erb
<h1 class="page-heading">All Pictures
	<small><%= @listing.title %></small>
</h1>
<div class="row">
	<div class="col-md-12">
		<%=link_to 'New', new_user_listing_picture_path, {class: "btn btn-primary btn-md"}%>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<% if @pictures.length == 0 %>
		  <p class="lead"> No pictures found </p>
		<% else %>
			<table class="table table-bordered table-striped table-responsive">
				<thead>
					<tr>
						<td>Title</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</thead>
				<tbody>
		      <% @pictures.each do |picture| %>
		      	<tr>
		      		<td><%= picture.title %></td>	
							<td><%= link_to "Show", user_listing_picture_path(@user, @listing, picture)%></td>
							<td><%= link_to "Edit", edit_user_listing_picture_path(@user, @listing, picture)%></td>
							<td><%= link_to "Delete", [@user, @listing, picture], method: :delete, data: {confirm: "Are you sure?"} %></td>
		      	</tr>
		      <% end %>
	    	</tbody>
			</table>
		<% end %>
  </div>
</div>

app/views/pictures/new.html.erb
<h1>New Picture</h1>
<%= render "form" %>

app/views/pictures/show.html.erb
<h1 class="page-heading">View Picture
	<small><%= @listing.title %></small>
</h1>

<p class="lead"><%= @picture.filename %> </p>

<div class="row">
	<div class="col-md-4">
		<div class="thumbnail">
			<img src= "/images/<%=@picture.filename%>" class="img-responsive" alt="picutre" />
			<div class="caption">
				<h3><%= @picture.title %></h3>
			</div>
		</div>
	</div>
</div>