config/routes.rb
Rails.application.routes.draw do

  root 'public#index'

  get "login" => "accounts#login", as: :login
  get "logout" => "accounts#logout", as: :logout

  post "authenticate" => "accounts#authenticate", as: :authenticate

  get "public/:listing_id/details" => "public#details", as: :details

  resources :users do
    resources :listings do
      resources :features
      resources :pictures
    end
  end

end

app/models/feature.rb
class Feature < ActiveRecord::Base
	validates :description, presence: true
	belongs_to :listing
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
	  def index
	  	@user = User.find(params[:user_id])
	  	@listing = Listing.find(params[:listing_id])
	  	@features = @listing.features
	  end

	  def new
	  	@user = User.find(params[:user_id])
	  	@listing = Listing.find(params[:listing_id])
	  	@feature = Feature.new
	  end

	  def create
	  	@listing = Listing.find(params[:listing_id])
	  	@feature = Feature.new(feature_params)
	  	@feature.listing = @listing
    	if @feature.save
      	redirect_to controller: "features", action: "index"
    	else
      render "new"
    	end
	  end

	  def edit
	  	@user = User.find(params[:user_id])
	  	@listing = Listing.find(params[:listing_id])
	  	@feature = Feature.find(params[:id])
	  end

	  def update
	  	@listing = Listing.find(params[:listing_id])
	  	@feature = Feature.find(params[:id])
	  	if @feature.update(feature_params)
      	redirect_to controller: "features", action: "index"
    	else
      render "new"
    	end
	  end

	  def destroy
	  @listing = Listing.find(params[:listing_id])
	  @feature = Feature.find(params[:id])
	  	if @feature.destroy
	  		redirect_to controller: "features", action: "index"
	  	else
	  		redirect_to controller: "features", action: "index"
	  	end
		end

	private

		def feature_params
			params.require(:feature).permit(:user_id, :listing_id, :description)
		end

end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_form.html.erb
<%= form_for [@user, @listing, @feature], :html => {:multipart => true, :class => "form-horizontal"} do |f| %>
	<% if @feature.errors.any? %>
  <div class="form-group">
  	<div id="error_explanation">
  		<h3>
  			<%= pluralize(@feature.errors.count, "error") %>
  			prohibited this picture from being saved.
  		</h3>
  	</div>
  </div>
	<% end %>

	<div class="form-group">
		<div class="control-label col-md-2">
			<%= f.label :description %>
			</div>
			<div class="col-md-4">
			<%= f.text_field :description, {:class => "form-control input-md", :maxlength => "140"} %>
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-12 text-center">
		<%= f.submit "Save", {class: "btn btn-primary btn-md"} %>
		</div>
	</div>


<% end %>

app/views/features/edit.html.erb
<h1>Edit Feature</h1>
<%= render "form" %>

app/views/features/index.html.erb
<h1 class="page-heading">All Features
	<small><%= @listing.title %></small>
</h1>
<div class="row">
	<div class="col-md-12">
		<%=link_to 'New', new_user_listing_feature_path, {class: "btn btn-primary btn-md"}%>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<% if @features.length == 0 %>
		  <p class="lead"> No features found </p>
		<% else %>
			<table class="table table-bordered table-striped table-responsive">
				<thead>
					<tr>
						<td>Description</td>
						<td></td>
						<td></td>
					</tr>
				</thead>
				<tbody>
		      <% @features.each do |feature| %>
		      	<tr>
		      		<td><%= feature.description %></td>
							<td><%= link_to "Edit", edit_user_listing_feature_path(@user, @listing, feature)%></td>
							<td><%= link_to "Delete", [@user, @listing, feature], method: :delete, data: {confirm: "Are you sure?"} %></td>
		      	</tr>
		      <% end %>
	    	</tbody>
			</table>
		<% end %>
  </div>
</div>

app/views/features/new.html.erb
<h1>New Feature</h1>
<%= render "form" %>